ll='ls -alF'

alias g='git'
alias ga='git add'
alias gd='gi diff'
alias gst='git status'
alias gsts='git status -s'
alias gp='git push'
alias gpush='git push'
alias gpull='git pull'
alias gb='git branch'
alias gco='git checkout'
alias gc='git commit'
alias gcm='git commit -m '
