alias ls='ls --color=auto' 
alias ll='ls -alF --color=auto'

alias g='git'
alias ga='git add'
alias gd='gi diff'
alias gst='git status'
alias gp='git push'
alias gpush='git push'
alias gpull='git pull'
alias gb='git branch'
alias gco='git checkout'
alias gc='git commit'
