name: test

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Install require packages
        run: apt-get update && apt-get install -y git sudo
      - uses: actions/checkout@v4
      - name: Run test
        working-directory: ./scripts
        run: install.sh
