name: test

on: [push]
jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
