name: test

on: [push]
jobs:
  docker-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Set metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{raw}}
            type=sha,format=short
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run: |
          docker compose build
          docker image ls

