name: test

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Install require packages
        run: apt-get update && apt-get -y git sudo
      - uses: actions/checkout@v4
      - name: git clone
        run: git clone https://github.com/yudai0804/dotfiles.git $HOME/dotfiles
      - name: Run test
        run: scripts/install.sh
