name: test

on: [push]
jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run: docker compose build
